### ISSUE TITLE
LongVersionOfTheDemo shows nothing

### ISSUE THREAD

**Issue by eggsyntax** [hchbaw/eval-sexp-fu.el#10]
On
https://github.com/hchbaw/eval-sexp-fu.el/wiki/LongVersionOfTheDemo

Nothing's there except the text "This is an eval-sexp-fu.el demo. (130 secs or so)". Is there supposed to be a video or something? I've checked in both Firefox & Chrome on OS X.

Thanks, and thanks for your work on this project!

**Comment by eggsyntax** [comment]
Additionally:

- The (presumably shorter) version is also missing.
- Checked on Firefox/Ubuntu as well, still nothing.

**Comment by hchbaw** [comment]
Thank you very much letting me know. I've uploaded images and updated the image links, thanks!
